---
title: "On Style"
bookToC: true
output: html_document
weight: 20
---

## "Frugging KCP" and "Fruggish" are intentionally irreverent, but I think Frug wouldn't mind. 

The following is from a section titled "On Style" in Frug's last work, "A Postmodern Feminist Legal Manifesto (An Unfinished Draft)."

#### The medium is the message
> *Style is important in postmodern work. The medium* is *the message, in some cases ... when style is salient, it is characterized by irony and by wordplay that is often dazzlingly funny, smart, and irreverent. Things aren't just what they seem.*

##### Mary Joe Frug, A Postmodern Feminist Legal Manifesto (An Unfinished Draft), Harvard Law Review 105 No. 5 1048 (Mar. 1992).


## Adjectivization

In a project that I co-authored (pending publication, so I'll be light on details) we reviewed a large sample of academic book reviews. Over 90 mens' names were somehow "adjectivized" within the reviews - Foucauldian, Wittgensteinian, Hegelian - or "nouned" - Marxism, Darwinism - as opposed to only three women. This coincided with a qualitative pattern of men writing *very* favorably about other men, to fairly adulatory extremes. 

The outcome we proposed in that paper is not that more women get sycophantic praise in book reviews, but to tone the personal veneration down in general. It can be dangerous to elevate scholars to lofty, elite status. Idolizing a certain person's (usually a certain man's) ideas can lead to the exclusion of new, challenging ideas, whether they be Jesus, Michel Foucault, or Tucker Carlson. Ideas should be challenged and reconsidered on a regular basis.

## It Sounds Funny 

So the choice of Frugging and Fruggish adopts this largely masculine technique - a sort of grammatical veneration, recognizing the greatness of (usually) *a man* and *his* ideas. I think Frug and Frug's ideas deserve acknowledgment, study, replication, respect, and even admiration, but part of a liberation-minded postmodernist study is questioning power and stopping short of veneration. 

#### Irony
> *Irony, for example, is a stylistic method of acknowledging and challenging a dominant meaning, of saying something and simultaneously denying it.*

##### Postmodern Feminist Legal Manifesto 1047.

So I am choosing to adjectivize and verbify Frug. I acknowledge the dominant meaning of adjectivization, which is heavily masculine and uncomfortably adulatory. So I do it, but challenge it at the same time: apply it to a woman, and make a bit of fun. I think that these grammatical techniques, notwithstanding their problematic connotations, are cool and interesting ways of honoring legacies. This project is directly inspired by Frug's work, so she ought to occupy a central position. I verbify and adjectivize with reservations, and I express my reservations through silliness. "Fruggish" says and denies itself. 
