---
title: "What Now?"
weight: 100
output: html_document
---

# Where Do We Go From Here?

I have some tentative recommendations that could be implemented either by Knapp, Crystal, and Prince in upcoming editions of their books or by professors who teach from KCP. 

My main criticism is not with KCP's case selection, as I think the gender imbalance is an unfortunate but accurate reflection of contract history. My gripe is with the notes. Overall, the notes after cases dealing with gender and race fail to meaningfully engage with the ideas. The casebook editors and/or professors teaching from the book could ameliorate this by grounding their discussion in critical scholarship and addressing some of the internal patterns revealed by this study.

I'm not at all qualified to give any comprehensive recommendations about what scholarship to reference, but I do have suggestions for places where it seems particularly appropriate to offer more context and criticism. 

### Concrete Suggestions for Editors and Professors

#### Scholarship

The casebook and courses based on it would benefit from more references to critical scholarship. 

1. I would recommend reference to critical legal thinkers in the introduction section of the book, giving students interested but undereducated about the field (like me) helpful starting places such as are provided for sociological jurisprudence (Pound), formalism (Langdell), legal realism (Llewellyn), etc.

2. [P.M. v. T.B.](/docs/race) cries out for a meaningful discussion of the role racism does and/or should play in legal decision-making. Reproductive justice is a very complex and rich field of study that often explicitly reckons with the issue. Again, I'm not nearly knowledgeable enough to presume to give recommendations for what a comprehensive discussion should look like: that said, to plug a distinguished professor and scholar at UPenn, where I go to school, Dorothy E. Roberts has some fascinating commentary on the implications of reproductive technologies for race, gender, class, disability, and the liberal notion of individual rights, such as ["Why Baby Markets Aren't Free."](https://www.law.uci.edu/lawreview/vol7/no3/Online_Roberts.pdf)

3. [King v. Trustees of Boston University](/docs/race) also gives an interesting opportunity to discuss the merits of a highly individualized, particularized civil system. The court only considers the individual claims of BU and the King family to the material, relegating the context of racism to a halfhearted mentioned of "volatile circumstances." Is it fair or just to analyze King's intent from a single letter, as opposed to the broader context in which he wrote it? 

4. To Knapp, Crystal, and Prince in particular, I want to commend some of notes, like the commentary on good faith after Locke v. Warner Bros. and the comment on the historical development of contractual capacity (pp. 589-591). I think the latter comment could be given a much more central position, ideally at the front of the book as critically important context for the entire field. 

#### This Study :)

In addition to incorporating more outside scholarship, some of the internal patterns revealed by this study merit mention. They reveal important inequalities and could prompt some very interesting conversations.

1. First, the overwhelmingly white masculine development of American public life in general and contract law in particular deserves a more central place in the book. With respect to gender, the basic observation that women constitute only a fourth (53 of 202) of individuals described in the case law merits mention. 

2. The prevalence of [widows](/docs/characters/characters3) is a very interesting quirk of the book. Husbandless women appear multiple times as vulnerable characters. They prompt some of the most emotionally charged opinions in the book, and potentially some thought-provoking conversations. Unmarried women, especially in the 19th and 20th centuries, did have particular vulnerabilities that made them good subjects for morally weighty opinions on unconscionability and good faith. The paternalism prompted by their vulnerability behooves their individuals outcomes (except in Kirksey, where the authors seem to be implicitly making the argument that it should have). But in a larger sense, does it harm more than it helps? Does it reinforce gender stereotypes? Or is this a good example of courts intervening in marginalization, which they fail to do in P.M. v. T.B or King v. Trustees of Boston University? Dohrmann v. Swaney and/or Syester v. Banta could use a note raising these questions. 

3. The massive proportion of [married women](/docs/characters/characters2) also deserves some attention. This could prompt conversations about barriers to entry in the legal system. Married women were not legally allowed to enter into contracts at all for much of Anglo and American history: are their rights still subsumed by their husbands? This is explored in the historical development of capacity note, which, as I recommend above, should be given a more central place. The disproportionality challenges KCP's statement that "this legal disability was removed by the passage of the Married Women's Property Acts:" while true in a strictly de jure legal sense, the historical issue seems to have long-ranging de facto consequences. 

I won't go so far as to make the other major finding a recommendation. The issue of potential [corporate masculinity](/docs/trying) seems to be an unexplored area of scholarly inquiry. Mentioning it to law students might prompt some interest in the subject and future study, which I personally think would be interesting. But it's less important than the above points. 

### Suggestions for Students

I encourage all law students to take an active, critical approach to their education. If your only goal is to absorb the doctrine as is, that's not education: it's indoctrination. 

1. Read your casebooks not as unquestionable authorities, but as historically located texts. 

2. Seek out critical commentary on legal doctrine and legal education. 

3. Talk to your professors and fellow students about the normative implications of the doctrine and the casebooks. 
